let shopItemsData = [
  {
    id: 1,
    name: "Noise deadset cancelling",
    price: 149.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Noise-cancelling.jpeg",
  },
  {
    id: 2,
    name: "Beats Studio3",
    price: 249.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Beats-Studio3.jpeg",
  },
  {
    id: 3,
    name: "Marshall Major iv",
    price: 149.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Marshall_Major-iv.jpeg",
  },
  {
    id: 4,
    name: "AKG N700NC",
    price: 199.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/AKG-N700NC.jpeg",
  },
  {
    id: 5,
    name: "Bose QC 45",
    price: 329.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Bose_QC-45.jpeg",
  },
  {
    id: 11,
    name: "Soundcore Q30",
    price: 89.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Soundcore-Q30.jpeg",
  },

  {
    id: 7,
    name: "Philips PH805",
    price: 109.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Philips-PH805.jpeg",
  },
  {
    id: 8,
    name: "Sennheiser HD 450BT",
    price: 119.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Sennheiser-HD-450BT.jpeg",
  },
  {
    id: 9,
    name: "Sony WH 10000XM4",
    price: 349.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/WH-10000XM4.jpeg",
  },
  {
    id: 10,
    name: "JBL Tune 750BTNC",
    price: 79.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/JBL_Tune-750BTNC.jpeg",
  },
   {
    id: 6,
    name: "Headset gaming",
    price: 129.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Headsetg-gaming.jpeg",
  },
 
  {
    id: 12,
    name: "headset bluetooth",
    price: 99.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/Headset-bluetooth.jpeg",
  },
];
